dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test postproc --keepdb
- rm local_settings.py
deploy:
  provider: heroku
  skip_cleanup: true
  app: decide-practica-fpg-1920
  strategy: git
  api_key:
    secure: BgWz71u9Msf3V4xp0y8evQqZtUqK+/MI7oBxT7G3Kdcna4bJBb6OD8TtIBPsnNMaqj2mzvqgoqlrUNMnsYrY2obOrvJtABqR6tdZA3pgi3edeRBGsm6rV1mUdEkm9hq7P3DhCP4LRk0WUdxDVxPVqvCDNKwk5c9V+cg5pA9C2AoBBdzQvqGr1i2SzvCIVEZ0vGcdyGw1lGjUL7uL6NdsF+PhU24x+jv1rUFclRe9u3FX1MIf7BAWNvcfl9rsHLcGrLj6O9RgFqzm/9ILyntxuLyza9i7XvNkNrer1MigdAuoPpYLIOx2GqpVPawdtR4xWUrfYVgCO+i24csOWU6nvhkEkb9S8A+Rd5hKFIZKuSMGChjwUHxNSboxUd9dSD2AulPaSJAswX3EvbZy9aJRnMmybOhl6Uq71p6Rv5qX5pEk5fhCyrw3tQ8qGKLaME90hYekktC6RKExjtmnqjC0XIG+OJ6nV36xDGTx3meGotlVd3KbHo+Vmt3vaGTFNgmWcBDfnpGG99zaOhNrOkmRV+P63hME0tzaUzZx97C8jWWpIxfidxeYhINjotojYKBP9A3B+yotW9h14KtR6dFCaKnFXUEydwRcjqLjIwqJgKSnsN2/G+5Q1nOqkHRiFKYZcRACjefNUdhTwf4qpt690d5AadLASBdPtfSltiLBjMk=
