dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  provider: heroku
  app: decide-practica-fpg-1920
  strategy: git
  api_key:
    secure: pgJ6kgWB0S36ZuU8oyA6umABKU3CWUHz8fX0bC+5c/SJydcB0JPaLxJ9fanL9Y4ajSzbQTbIR+HExXCq3p4XhB81sMCgWA03OrFrjLfyDSWX5zDvJ8SKjx7FLxKol0MSRPgE/k+oRzuZqnsxR3GEWCOOXRxE/xksRZi+xfTloKu8wPaFbbp/ZKJWwDo07uXLGQck6p6XefUIjMdKdbcG1B3PnHppe/cBbcdRJWN7+N/By3FIn02Gl/LrV/VuukFF5uR1g+0xuBunLhbaKlJ/DrHlG+kWCbh7X7BPsDILLKOHgpTtyaeLMcSmGDkhwOCIesYL/Ys6LWYZTqlO4hNracgQpX9V52LMoGneaD5JODqzgf5na3NY+Qtvamo65EvLpSWSwNt9s6sfCA8NDR2/dr1cqP7VaB+6eszonkOudvQt7BLpr/rc46XFNyFj9OcXTMI+EnytOxGX3tfq4eO5THhxswSrxVOBNI5XlUD+K3NrxCj0Bk9jqdwmRL90BHgkI9lDJ5U6If1lrfypZXiUniEiNAU2ZKNEaeyBgJ08ISecky6H93Bio0ivklAjBxl43Dqh2FsH0puReS30HKCFKnEcs49+h3iSKYl/bs0xg0M4XMamOfRq2QBvnibfv/GpPkG3uoIp9rx7RM0SqNXuqMSu2JS9g2IPwX36dTpy7UU=
